CREATE TABLE IF NOT EXISTS "seu_assessments" (
  "id" serial PRIMARY KEY NOT NULL,
  "company_id" integer DEFAULT 1 NOT NULL REFERENCES "companies"("id"),
  "unit_id" integer REFERENCES "units"("id") ON DELETE CASCADE,
  "year" integer NOT NULL,
  "period_start" integer DEFAULT 1 NOT NULL,
  "period_end" integer DEFAULT 12 NOT NULL,
  "analysis_level" text DEFAULT 'energyUseGroup' NOT NULL,
  "method_type" text DEFAULT 'consumption_share_opportunity_matrix' NOT NULL,
  "record_type" text DEFAULT 'unit_official' NOT NULL,
  "is_official" boolean DEFAULT true NOT NULL,
  "unit_total_tep" real DEFAULT 0 NOT NULL,
  "energy_source_id" integer REFERENCES "energy_sources"("id") ON DELETE SET NULL,
  "created_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "updated_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "seu_assessment_items" (
  "id" serial PRIMARY KEY NOT NULL,
  "assessment_id" integer NOT NULL REFERENCES "seu_assessments"("id") ON DELETE CASCADE,
  "energy_use_group_id" integer REFERENCES "energy_use_groups"("id") ON DELETE SET NULL,
  "meter_id" integer REFERENCES "meters"("id") ON DELETE SET NULL,
  "unit_id" integer REFERENCES "units"("id") ON DELETE SET NULL,
  "sub_unit_id" integer REFERENCES "sub_units"("id") ON DELETE SET NULL,
  "energy_source_id" integer REFERENCES "energy_sources"("id") ON DELETE SET NULL,
  "name" text NOT NULL,
  "energy_tep" real DEFAULT 0 NOT NULL,
  "consumption_share_percent" real DEFAULT 0 NOT NULL,
  "has_opportunity" boolean DEFAULT false NOT NULL,
  "priority_result" integer,
  "system_recommendation" text DEFAULT 'not_seu' NOT NULL,
  "user_decision" text,
  "decision_reason" text,
  "responsible" text,
  "target_reduction_percent" real,
  "notes" text,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);
